<?php
return  [
	'K_Patient_ID'     => 'K_Patient_ID',
	
	'PT_First'         => 'PatientFirst',
	'PT_DOB'           => 'PatientDOB',
	'PT_PhoneHome'     => 'PatientPhone',
	'PT_PhoneAlt'      => 'PT_PhoneAlt',
	'PT_City'          => 'PatientCity',
	'PT_Middle'        => 'PatientMidInit',
	'PT_Last'          => 'PatientLast',
	'PT_StreetAddress' => 'PatientStreetAddress',
	'PT_Zip'           => 'PatientZip',
	'PT_Ethnicity'     => 'PT_Ethnicity',
	'PT_Email'         => 'PT_Email',
	'PT_Gender_Male'   => 'PatientMale',
	'PT_State'         => 'PatientState',
	
	'PT_MaritalSingle'  => 'PatientMaritalSingle',
	'PT_MaritalMarried' => 'PatientMaritalMarried',
	'PT_MaritalOther'   => 'PatientMaritalOther',
	
	'Legal_InterpreterNeeded'        => 'Legal_InterpreterNeeded',
	'Legal_AdvancedDirectiveOffered' => 'Legal_AdvancedDirectiveOffered',
	'AdvancedDirectiveTaken'         => 'AdvancedDirectiveTaken',

	'Insurance_PlanName'                 => 'Insurance_PlanName',
	'Insurance_PayorID'                  => 'Insurance_PayorID',
	'Insurance_IssueDate'                => 'Insurance_IssueDate',
	'InsuranceSecond_PlanName'           => 'InsuranceSecond_PlanName',
	'InsuranceSecond_PayorID'            => 'InsuranceSecond_PayorID',
	'InsuranceSecond_IssueDate'          => 'InsuranceSecond_IssueDate',
	
	'TB_Type'                            => 'TB_Type',
	'TB_Size'                            => 'TB_Size',
	'TB_RiskAssessment'                  => 'TB_RiskAssessment',
	'TB_Result'                          => 'TB_Result',
	'TB_ReadBy'                          => 'TB_ReadBy',
	'TB_Induration'                      => 'TB_Induration',
	'TB_DateRead'                        => 'TB_DateRead',
	'TB_Date'                            => 'TB_Date',
	'TB_ChestXRay'                       => 'TB_ChestXRay',
	'Notes'                              => 'Notes',
	
	'HistorySelf_Surgeries'              => 'HistorySelf_Surgeries',
	'HistorySelf_LastInfluenza'          => 'HistorySelf_LastInfluenza',
	'HistorySelf_LastChlamydia'          => 'HistorySelf_LastChlamydia',
	'HistorySelf_LastPhysical'           => 'HistorySelf_LastPhysical',
	'HistorySelf_LastSHA'                => 'HistorySelf_LastSHA',
	'HistorySelf_LastCholesterol'        => 'HistorySelf_LastCholesterol',
	'HistorySelf_LastFOBT'               => 'HistorySelf_LastFOBT',
	'HistorySelf_Colonoscopy'            => 'HistorySelf_Colonoscopy',
	'HistorySelf_SIG'                    => 'HistorySelf_SIG',
	'HistorySelf_ECG1'                   => 'HistorySelf_ECG1',
	'HistorySelf_ECG2'                   => 'HistorySelf_ECG2',
	'HistorySelf_PPD1'                   => 'HistorySelf_PPD1',
	'HistorySelf_PPD2'                   => 'HistorySelf_PPD2',
	'HistorySelf_Tetanous1'              => 'HistorySelf_Tetanous1',
	'HistorySelf_Tetanous2'              => 'HistorySelf_Tetanous2',
	'HistorySelf_LastPneumo'             => 'HistorySelf_LastPneumo',
	'HistorySelf_DM'                     => 'HistorySelf_DM',
	'HistorySelf_HTN'                    => 'HistorySelf_HTN',
	'HistoryFam_HTN'                     => 'HistoryFam_HTN',
	'HistorySelf_Asthma'                 => 'HistorySelf_Asthma',
	'HistoryFam_Asthma'                  => 'HistoryFam_Asthma',
	'HistorySelf_Cancer'                 => 'HistorySelf_Cancer',
	'HistoryFam_Cancer'                  => 'HistoryFam_Cancer',
	'HistorySelf_ChestPain'              => 'HistorySelf_ChestPain',
	'HistorySelf_Palpitation'            => 'HistorySelf_Palpitation',
	'HistorySelf_HistOfMI'               => 'HistorySelf_HistOfMI',
	'HistorySelf_Tuberculosis'           => 'HistorySelf_Tuberculosis',
	'HistorySelf_ChronicCough'           => 'HistorySelf_ChronicCough',
	'HistorySelf_ShortnessOfBreath'      => 'HistorySelf_ShortnessOfBreath',
	'HistorySelf_Bronchitis'             => 'HistorySelf_Bronchitis',
	'HistorySelf_Bronchitis'             => 'HistorySelf_Bronchitis',
	'HistorySelf_BreastProblems'         => 'HistorySelf_BreastProblems',
	'HistorySelf_PainfulUrination'       => 'HistorySelf_PainfulUrination',
	'HistorySelf_BloodInUrin'            => 'HistorySelf_BloodInUrin',
	'HistorySelf_RenalStones'            => 'HistorySelf_RenalStones',
	'HistorySelf_ProstateProblems'       => 'HistorySelf_ProstateProblems',
	'HistorySelf_RecentHospitalizations' => 'HistorySelf_RecentHospitalizations',
	'HistorySelf_ChronicDiarrea'         => 'HistorySelf_ChronicDiarrea',
	'HistorySelf_Constipation'           => 'HistorySelf_Constipation',
	'HistorySelf_StomachUlcers'          => 'HistorySelf_StomachUlcers',
	'HistorySelf_Gastritis'              => 'HistorySelf_Gastritis',
	'HistorySelf_LiverProblems'          => 'HistorySelf_LiverProblems',
	'HistorySelf_RectalBleeding'         => 'HistorySelf_RectalBleeding',
	'HistorySelf_GallbladderProblems'    => 'HistorySelf_GallbladderProblems',
	'HistorySelf_WeightLoss'             => 'HistorySelf_WeightLoss',
	'HistorySelf_Strokes'                => 'HistorySelf_Strokes',
	'HistorySelf_Seizures'               => 'HistorySelf_Seizures',
	'HistorySelf_LossConciousness'       => 'HistorySelf_LossConciousness',
	'HistorySelf_MentalProblems'         => 'HistorySelf_MentalProblems',
	'HistorySelf_VisualProblems'         => 'HistorySelf_VisualProblems',
	'HistorySelf_HearingProblems'        => 'HistorySelf_HearingProblems',
	'HistorySelf_ThyroidProblems'        => 'HistorySelf_ThyroidProblems',
	'HistorySelf_SkinLesions'            => 'HistorySelf_SkinLesions',
	'HistorySelf_Glaucoma'               => 'HistorySelf_Glaucoma',
	'HistorySelf_JointProblems'          => 'HistorySelf_JointProblems',
	'HistorySelf_Fractures'              => 'HistorySelf_Fractures',
	'HistorySelf_Arthritis'              => 'HistorySelf_Arthritis',
	'HistorySelf_BackPain'               => 'HistorySelf_BackPain',
	'HistorySelf_PAP1'                   => 'HistorySelf_PAP1',
	'HistorySelf_Mamogram1'              => 'HistorySelf_Mamogram1',

	'HistorySelf_Tobacco'				 => 'HistorySelf_Tobacco',
	'HistorySelf_Alchohol'				 => 'HistorySelf_Alchohol',
	'HistorySelf_Drugs'					 => 'HistorySelf_Drugs',

	'Precnancies_BirthControl'           => 'Precnancies_BirthControl',
	'Precnancies_Successful'             => 'Precnancies_Successful',
	'Precnancies_Csections'              => 'Precnancies_Csections',
	'Precnancies_Abortions'              => 'Precnancies_Abortions',
	//update - escondido
	'Precnancies_LastPAP'  => 'Precnancies_LastPAP',
	'Precnancies_LastMamo' => 'Precnancies_LastMamo',
	//end update
	'Report_MembershipType'  => 'Report_MembershipType',
	'Report_MembershipNotes' => 'Report_MembershipNotes',
	'Report_MembershipDate'  => 'Report_MembershipDate',
	'Report_Membership'      => 'Report_Membership',
	'Report_HowDidYouFindUs' => 'Report_HowDidYouFindUs',

	'Guardian_Zip'          => 'Guardian_Zip',
	'Guardian_State'        => 'Guardian_State',
	'Guardian_PhoneHome'    => 'Guardian_PhoneHome',
	'Guardian_PhoneAlt'     => 'Guardian_PhoneAlt',
	'Guardian_Middle'       => 'Guardian_Middle',
	'Guardian_Last'         => 'Guardian_Last',
	'Guardian_GenderMale'   => 'Guardian_GenderMale',
	'Guardian_GenderFemale' => 'Guardian_GenderFemale',
	'Guardian_First'        => 'Guardian_First',
	'Guardian_City'         => 'Guardian_City',
	'Guardian_Address'      => 'Guardian_Address',
	
	'EmergencyContact_Zip'       => 'EmergencyContact_Zip',
	'EmergencyContact_State'     => 'EmergencyContact_State',
	'EmergencyContact_Relation'  => 'EmergencyContact_Relation',
	'EmergencyContact_PhoneHome' => 'EmergencyContact_PhoneHome',
	'EmergencyContact_PhoneAlt'  => 'EmergencyContact_PhoneAlt',
	'EmergencyContact_Middle'    => 'EmergencyContact_Middle',
	'EmergencyContact_Last'      => 'EmergencyContact_Last',
	'EmergencyContact_First'     => 'EmergencyContact_First',
	'EmergencyContact_City'      => 'EmergencyContact_City',
	'EmergencyContact_Address'   => 'EmergencyContact_Address',
];