<?php
return [
	'FK_Patient_ID'        => 'FK_Patient_ID',
	'K_Encounter_ID'       => 'K_Encounter_ID',
	'str_doctor_signature' => 'Staff_DoctorSignature',
	'date_signature'       => 'DOS',
	'pat_education'        => 'POST_EducationDiscussed',
	'method_payment'       => 'Info_VisitInsurance',
	'visit_type'           => 'Info_VisitType',
	'blood_pressure_sys'   => 'Vitals_BPsys',
	'blood_pressure_dia'   => 'Vitals_BPdia',
	
	'chief_complaint'             => 'Vitals_ChiefComplaint',
	'heart_pulse'                 => 'Vitals_Pulse',
	'heart_respiratory'           => 'Vitals_Respiratory',
	'heart_temperature'           => 'Vitals_Temperature',
	'heart_hemoglobin'            => 'Physical_Hemoglobin',
	'heart_hematocrit'            => 'Physical_Hematocrit',
	'heart_head_circ'             => 'Physical_HeadCircumference',
	'heart_last_menstrual_period' => 'Pregnancies_LastPAP',
	'physical_birth_weight'       => 'Physical_BirthWeight',
	'physical_weight'             => 'Vitals_Weight',
	'physical_height'             => 'Vitals_Height',
	'eye_left'                    => 'Vitals_EyeL',
	'eye_right'                   => 'Vitals_EyeR',
	'eye_both'                    => 'Vitals_EyeBoth',
	'eye_glasess'                 => 'Vitals_EyeWereGlassesWornDuringExam',
	'done_at'                     => 'Billing_PrintedDate',

	'audio_left_1000'             => 'Vitals_HearingL1',
	'audio_left_2000'             => 'Vitals_HearingL2',
	'audio_left_3000'             => 'Vitals_HearingL3',
	'audio_left_4000'             => 'Vitals_HearingL4',
	'audio_right_1000'            => 'Vitals_HearingR1',
	'audio_right_2000'            => 'Vitals_HearingR2',
	'audio_right_3000'            => 'Vitals_HearingR3',
	'audio_right_4000'            => 'Vitals_HearingR4',
	
	'urinalysis_color'            => 'Urinaylsis_Color',
	'urinalysis_specific_gravity' => 'Urinalysis_SpecGravity',
	'urinalysis_ph'               => 'Urinalysis_PH',
	'urinalysis_protein'          => 'Urinalysis_Protein',
	'urinalysis_glucose'          => 'Urinaylsis_Glucose',
	'urinalysis_ketones'          => 'Urinalysis_Ketones',
	'urinalysis_bilirubim'        => 'Urinaylsis_Bilirubin',
	'urinalysis_blood'            => 'Urinalysis_blood',
	'urinalysis_leuktocytes'      => 'Urinalysis_Leukocytes',
	'urinalysis_nitrite'          => 'Urinalysis_Nitrite',
	
	'procedure_text'          => 'POST_Procedures',
	'present_illness_history' => 'POST_PresentIllnessHistory',
	'request_xray'            => 'POST_Xray',
	
	'checkedout_signed' 	   => 'Invoice_CheckoutMA',
	//invoice
	'invoice_office_visit'      => 'Invoice_OV',
	'invoice_laboratories'      => 'Invoice_Lab',
	'invoice_injections'        => 'Invoice_Injection',
	'invoice_medications'       => 'Invoice_Meds',
	'invoice_procedures'        => 'Invoice_Procedures',
	'invoice_physical'          => 'Invoice_INS',
	'invoice_ecg'               => 'Invoice_ECG',
	'invoice_ultrasound'        => 'Invoice_Ultrasound',
	'invoice_x_ray'             => 'Invoice_XRay',
	'invoice_subtotal'          => 'Invoice_SubTotal',
	'invoice_paid'              => 'Invoice_Paid',
	'invoice_open_balance'      => 'Invoice_OpenBalance',
	'invoice_discount'          => 'Invoice_Discount',
	'invoice_total'             => 'Invoice_Total',
	'invoice_payment_type'      => 'Invoice_MethodPaid',
	'invoice_discount_type'     => 'Invoice_DiscountType',

	//billing
	'str_bill_signature'  => 'Billing_Info_BilleyBy',
	'federal_tax_id'      => 'Billing_TaxID',
	'outside_lab_charges' => 'Billing_OutsideLabCharges',

	'Billing_Insured_Last'                            => 'Billing_Insured_Last',
	'Billing_Insured_First'                           => 'Billing_Insured_First',
	'Billing_Insured_Middle'                          => 'Billing_Insured_Middle',
	'Billing_Insured_City'                            => 'Billing_Insured_City',
	'Billing_Insured_State'                           => 'Billing_Insured_State',
	'Billing_Insured_Zip'                             => 'Billing_Insured_Zip',
	'Billing_Insured_Phone'                           => 'Billing_Insured_Phone',
	'Billing_Insured_StreetAddress'                   => 'Billing_Insured_StreetAddress',
	'Billing_OtherInsured_Last'                       => 'Billing_OtherInsured_Last',
	'Billing_OtherInsured_First'                      => 'Billing_OtherInsured_First',
	'Billing_OtherInsured_Middle'                     => 'Billing_OtherInsured_Middle',
	'Billing_OtherInsured_PolicyOrGroupNumber'        => 'Billing_OtherInsured_PolicyOrGroupNumber',
	'Billing_OtherInsured_InsurancePlanOrProgramName' => 'Billing_OtherInsured_InsurancePlanOrProgramName',
	'Billing_Plan_Medicare'                           => 'Billing_Plan_Medicare',
	'Billing_Plan_Medicaid'                           => 'Billing_Plan_Medicaid',
	'Billing_Plan_Champus'                            => 'Billing_Plan_Champus',
	'Billing_Plan_Champva'                            => 'Billing_Plan_Champva',
	'Billing_Plan_GroupHealthPlan'                    => 'Billing_Plan_GroupHealthPlan',
	'Billing_Plan_FECA'                               => 'Billing_Plan_FECA',
	'Billing_Plan_Other'                              => 'Billing_Plan_Other',
	'Billing_InsuranceRelation_self'                  => 'Billing_InsuranceRelation_self',
	'Billing_InsuranceRelation_spouce'                => 'Billing_InsuranceRelation_spouce',
	'Billing_InsuranceRelation_child'                 => 'Billing_InsuranceRelation_child',
	'Billing_InsuranceRelation_other'                 => 'Billing_InsuranceRelation_other',
	//can be change?
	'write_off_6'     => 'Billing_WriteOff6',
	'write_off_5'     => 'Billing_WriteOff5',
	'write_off_4'     => 'Billing_WriteOff4',
	'write_off_3'     => 'Billing_WriteOff3',
	'write_off_2'     => 'Billing_WriteOff2',
	'write_off_1'     => 'Billing_WriteOff1',
	'paid_6'          => 'Billing_Paid6',
	'paid_5'          => 'Billing_Paid5',
	'paid_4'          => 'Billing_Paid4',
	'paid_3'          => 'Billing_Paid3',
	'paid_2'          => 'Billing_Paid2',
	'paid_1'          => 'Billing_Paid1',
	'total_paid'      => 'Billing_PaidTotal',
	'total_write_off' => 'Billing_WriteOffTotal',
	'total_due'       => 'Billing_BalanceDue',
	'comments'        => 'Billing_Info_Comments',
	'bill_status'     => 'Billing_Info_PaymentStatus',
	//
	'total_charge'                         => 'TotalCharges',
	'patient_condition_employment'         => 'ConditionRelatedToEmploymentYes',
	'patient_condition_autoaccident'       => 'ConditionRelatedToAutoAccidentYes',
	'patient_condition_autoaccident_place' => 'AutoAccidentState',
	'patient_condition_otheraccident'      => 'ConditionRelatedToOtherAccidentYes',
	'date_patient_work_from'               => 'UnableToWorkToDate',
	'date_patient_work_to'                 => 'UnableToWorkFromDate',
	'diagnosis_illness_a'                  => 'DiagCode1',
	'diagnosis_illness_b'                  => 'DiagCode2',
	'diagnosis_illness_c'                  => 'DiagCode3',
	'diagnosis_illness_d'                  => 'DiagCode4',
	'diagnosis_illness_e'                  => 'DiagCode5',
	'diagnosis_illness_f'                  => 'DiagCode6',
	'diagnosis_illness_g'                  => 'DiagCode7',
	'diagnosis_illness_h'                  => 'DiagCode8',
	'resubmission_code'                    => 'MedicaidResubCode',
	'original_ref_no'                      => 'MedicaidRefNumber',
	'authorization_number'                 => 'PriorAuthNo',
	'accept_assignment'                    => 'AcceptAssignmentYes',
	
	'place_of_service_1'                   => 'PlaceOfService1',
	'emg_1'                                => 'EMG1',
	'procedure_cpt_hcpcs_1'                => 'CPT1',
	'modifier_a_1'                         => 'ModifierA1',
	'modifier_b_1'                         => 'ModifierB1',
	'modifier_c_1'                         => 'ModifierC1',
	'modifier_d_1'                         => 'ModifierD1',
	'diagnosis_pointer_1'                  => 'DiagCodePointer1',
	'charges_1'                            => 'Charges1',
	'days_units_1'                         => 'Units1',
	'family_plan_1'                        => 'EPSDT1',
	'id_qual_1'                            => 'RenderingPhysQualifier1',
	'rendering_provider_id_1'              => 'RenderingPhysID1',
	'rendering_provider_npi_1'             => 'RenderingPhysNPI1',
	
	'place_of_service_2'                   => 'PlaceOfService2',
	'emg_2'                                => 'EMG2',
	'procedure_cpt_hcpcs_2'                => 'CPT2',
	'modifier_a_2'                         => 'ModifierA2',
	'modifier_b_2'                         => 'ModifierB2',
	'modifier_c_2'                         => 'ModifierC2',
	'modifier_d_2'                         => 'ModifierD2',
	'diagnosis_pointer_2'                  => 'DiagCodePointer2',
	'charges_2'                            => 'Charges2',
	'days_units_2'                         => 'Units2',
	'family_plan_2'                        => 'EPSDT2',
	'id_qual_2'                            => 'RenderingPhysQualifier2',
	'rendering_provider_id_2'              => 'RenderingPhysID2',
	'rendering_provider_npi_2'             => 'RenderingPhysNPI2',
	
	'place_of_service_3'                   => 'PlaceOfService3',
	'emg_3'                                => 'EMG3',
	'procedure_cpt_hcpcs_3'                => 'CPT3',
	'modifier_a_3'                         => 'ModifierA3',
	'modifier_b_3'                         => 'ModifierB3',
	'modifier_c_3'                         => 'ModifierC3',
	'modifier_d_3'                         => 'ModifierD3',
	'diagnosis_pointer_3'                  => 'DiagCodePointer3',
	'charges_3'                            => 'Charges3',
	'days_units_3'                         => 'Units3',
	'family_plan_3'                        => 'EPSDT3',
	'id_qual_3'                            => 'RenderingPhysQualifier3',
	'rendering_provider_id_3'              => 'RenderingPhysID3',
	'rendering_provider_npi_3'             => 'RenderingPhysNPI3',
	
	'place_of_service_4'                   => 'PlaceOfService4',
	'emg_4'                                => 'EMG4',
	'procedure_cpt_hcpcs_4'                => 'CPT4',
	'modifier_a_4'                         => 'ModifierA4',
	'modifier_b_4'                         => 'ModifierB4',
	'modifier_c_4'                         => 'ModifierC4',
	'modifier_d_4'                         => 'ModifierD4',
	'diagnosis_pointer_4'                  => 'DiagCodePointer4',
	'charges_4'                            => 'Charges4',
	'days_units_4'                         => 'Units4',
	'family_plan_4'                        => 'EPSDT4',
	'id_qual_4'                            => 'RenderingPhysQualifier4',
	'rendering_provider_id_4'              => 'RenderingPhysID4',
	'rendering_provider_npi_4'             => 'RenderingPhysNPI4',
	
	'place_of_service_5'                   => 'PlaceOfService5',
	'emg_5'                                => 'EMG5',
	'procedure_cpt_hcpcs_5'                => 'CPT5',
	'modifier_a_5'                         => 'ModifierA5',
	'modifier_b_5'                         => 'ModifierB5',
	'modifier_c_5'                         => 'ModifierC5',
	'modifier_d_5'                         => 'ModifierD5',
	'diagnosis_pointer_5'                  => 'DiagCodePointer5',
	'charges_5'                            => 'Charges5',
	'days_units_5'                         => 'Units5',
	'family_plan_5'                        => 'EPSDT5',
	'id_qual_5'                            => 'RenderingPhysQualifier5',
	'rendering_provider_id_5'              => 'RenderingPhysID5',
	'rendering_provider_npi_5'             => 'RenderingPhysNPI5',
	
	'place_of_service_6'                   => 'PlaceOfService6',
	'emg_6'                                => 'EMG6',
	'procedure_cpt_hcpcs_6'                => 'CPT6',
	'modifier_a_6'                         => 'ModifierA6',
	'modifier_b_6'                         => 'ModifierB6',
	'modifier_c_6'                         => 'ModifierC6',
	'modifier_d_6'                         => 'ModifierD6',
	'diagnosis_pointer_6'                  => 'DiagCodePointer6',
	'charges_6'                            => 'Charges6',
	'days_units_6'                         => 'Units6',
	'family_plan_6'                        => 'EPSDT6',
	'id_qual_6'                            => 'RenderingPhysQualifier6',
	'rendering_provider_id_6'              => 'RenderingPhysID6',
	'rendering_provider_npi_6'             => 'RenderingPhysNPI6',
	
	/**
	 * Physical Added 2018 - Marzo 12
	 */
//#BASIC
	'ethnic_code'     => 'Physical_EthnicCode',
	'screen_periodic' => 'Physical_ScreenTypePeriodic',
	'screen_initial'  => 'Physical_ScreenTypeInitial',
	'referred_to_wic' => 'Physical_Referred to WIC',
	'enrolled_in_wic' => 'Physical_Enrolled In WIC',
	'treatment'       => 'Physical_Treatment',
	'assessment'       => 'Physical_Assessment',
	'tb_risk'         => 'Physical_TbRiskAssessment',
	'lead_risk'       => 'Physical_LeadRiskQuestionaire',
//#INTERVAL HISTORY
	'interval_history_diet'              => 'Physical_Diet',
	'interval_history_illness'           => 'Physical_Illness',
	//'interval_history_problems'        => '**',
	'interval_history_immunization'      => 'Physical_ImmunizationReaction',
	'interval_history_parental_concerns' => 'Physical_ParentalConcern',
//#DEVELOPMENT
	'has_development' 	  => 'Physical_Development',
	'development_result'  => 'Physical_DevelopmentTests',
	//'development_options' => 'Physical_DevelopmentTests'
	//'development_plan'  => ''
//#PHYSICAL EXAMINATION
	'physical_comments_general_appearance' => 'POST_GeneralApearance',
	'physical_comments_nutrition'          => 'Physical_Nutrition',
	'physical_comments_skin'               => 'POST_Skin',
	'_physical_comments_head'              => 'Physical_Head',
	'_physical_comments_neck'              => 'Physical_Neck',
	'_physical_comments_nodes'             => 'Physical_Nodes',
	'physical_comments_eyes_eq_reflex'     => 'Physical_LightReflex',
	'physical_comments_ent_hearing'        => 'Physical_ETNhearing',
	'physical_comments_mouth_dental'       => 'Physical_MouthDental',
	'physical_comments_chest_lungs'        => 'Physical_ChestLungs',
	'physical_comments_heart'              => 'POST_Heart',
	'physical_comments_abdomen'            => 'POST_Abdomen',
	'physical_comments_external_genitalia' => 'Physical_ExtGenitalia',
	'physical_comments_back'               => 'Physical_Back',
	'physical_comments_extremities_hips'   => 'Physical_Extremities',
	'physical_comments_neurological'       => 'POST_Neurological',
	'physical_comments_fem_pulses'         => 'Physical_FemPulses',
//#EDUCATIONS
	'educations' => 'Physical_Education',
//#TOBACCO
	'tobacco_patient_exposed'     => 'Physical_ExposedToSecondHandSmoke',
	'tobacco_used_by_patient'     => 'Physical_Smokes',
	'tobacco_prevention_referred' => 'Physical_TobaccoPrevention',

];