<?php
return [
	'appointments' => [
		'create',
		'update',
		'cancel',
		'updateAll',
		'cancellAll',
		'setArrival',
		'setWithMA',
		'setRoom',
		'setDone',
	],
	'patients' => [
		'list',
		'create',
		'updateAbout',
		'updateInsurances',
		'updateAddress',
		'updateMembership',
		'updatePreventions',
		'updateResponsibleParty',
		'updateEmergencyContact',
		'addWarnings',
		'removeWarnings',
		'showAppointments',
		'printDemographics',
	],
	'patientChart' => [
		'addFiles',
		'addEncounter',
		'addCommunications',
		'updateVaccines',
		'updateHealthHistory',
		'updateAbortion',
		'updateTuberculosis',
		'showChronicMedications',
		'showChronicDiagnosis'
	],
	'encounters' => [
		'list',
		'create',
		'updateVitals',
		'updatePresentIllness',
		'updatePhysicalExam',
		'updateDiagnosis',
		'updateMedications',
		'updateRequests',
		'updateReferrals',
		'updateProcedure',
		'updateEducation',
		'updateChildPhysical',
		'showOptionCompare',
		'showOptionHistory',
		'signEncounter',
		'addAddendums',
	]
];